# Generated by Django 4.1.4 on 2023-03-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
