# Generated by Django 4.1.4 on 2023-03-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
    ]
