# Generated by Django 4.1.4 on 2023-03-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_review_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_tb',
        ),
    ]
