# Generated by Django 4.1.4 on 2023-02-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('code', models.CharField(max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceadmin.admin')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
